# Generated by Django 4.2.5 on 2023-10-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_comptebancaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='compteclient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_bancaire_client', to='tiers.fournisseur'),
        ),
    ]
