# Generated by Django 4.2.5 on 2023-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libellé', models.CharField(max_length=100)),
                ('categoryDesc', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('MotherCategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='produits.category')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence interne pour ce produit', max_length=120, unique=True, verbose_name='Référence du produit')),
                ('name', models.CharField(help_text='La désignation du produit', max_length=200, null=True, verbose_name='Désignation')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva_douan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('initial_qte', models.IntegerField()),
                ('TotalQte', models.IntegerField(default=0)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='produits.category')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='Variantes_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_lib', models.CharField(max_length=100)),
                ('values_list', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeArchive', models.CharField(max_length=255)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_set', to='produits.product')),
                ('variant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_set', to='produits.variantes_product')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductVerificationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(max_length=255)),
                ('realQuantity', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('verification_result', models.BooleanField()),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_verification', to='produits.verificationarchive')),
            ],
        ),
        migrations.CreateModel(
            name='historique_prix_achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('prix_achat_original', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_achat_newer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='produits.product')),
            ],
        ),
    ]
