# Generated by Django 4.2.5 on 2023-09-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0002_alter_typeclient_type_desc'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='variantsPrixClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('produit', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='produit_var', to='produits.product')),
                ('type_client', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='prix_var', to='clientInfo.typeclient')),
            ],
        ),
    ]
