# Generated by Django 4.2.5 on 2023-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0002_variantsprixclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reforme",
            field=models.BooleanField(default=False),
        ),
    ]
