# Generated by Django 4.2.5 on 2023-10-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0005_verificationarchive_entrepot"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="parent_product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="myvariants",
                to="produits.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="produits.category",
            ),
        ),
    ]
