# Generated by Django 4.1.7 on 2023-12-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pc_component',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
