# Generated by Django 4.1.7 on 2023-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_category_pc_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
