# Generated by Django 3.2.14 on 2024-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_numseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_vente_pc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='variantsprixclient',
            name='prix_vente_pc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
