# Generated by Django 3.2.14 on 2024-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0014_auto_20240403_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='kitcomponents',
            field=models.TextField(default=''),
        ),
    ]
