# Generated by Django 4.2.5 on 2024-05-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0010_auto_20240304_1334'),
        ('produits', '0015_auto_20240513_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_pc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_vente_kit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='produits.product')),
                ('type_client', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='clientInfo.typeclient')),
            ],
        ),
    ]
