# Generated by Django 4.2.5 on 2024-05-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0018_promotion_prix_vente_carton'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('produit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moncodeEAN', to='produits.product')),
            ],
        ),
    ]
