# Generated by Django 4.2.5 on 2024-03-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_entrepots_responsible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="adresse_ip",
            field=models.GenericIPAddressField(
                blank=True, default="127.0.0.1", null=True
            ),
        ),
    ]
