# Generated by Django 4.2.5 on 2023-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('clientInfo', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_clients', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='banque',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_store', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='agence',
            name='banque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_agence', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='agence',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_store', to='clientInfo.store'),
        ),
    ]
