# Generated by Django 4.2.5 on 2023-09-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_tierscustompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelCompte', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('TypeCompte', models.TextField(blank=True, null=True)),
                ('num_compte', models.IntegerField(blank=True, null=True)),
                ('cle', models.IntegerField(blank=True, null=True)),
                ('IBAN', models.IntegerField(blank=True, null=True)),
                ('Agence', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_banque_client', to='tiers.agence')),
                ('Banque', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_banque_client', to='tiers.banque')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_bancaire_client', to='tiers.client')),
            ],
        ),
    ]
