# Generated by Django 4.2.5 on 2023-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiers", "0006_remove_client_actclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Nif",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="Nis",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="num_article",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="region_client",
            field=models.CharField(default="", max_length=150),
        ),
    ]
