# Generated by Django 4.2.5 on 2023-10-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_logentry_mylogentry'),
        ('tiers', '0007_client_nif_client_nis_client_num_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_clients', to='users.customuser'),
        ),
    ]
