# Generated by Django 3.2.14 on 2024-03-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sourceClient',
            field=models.CharField(default='', max_length=150),
        ),
    ]
