# Generated by Django 3.2.14 on 2024-05-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0010_client_sourceclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='AIDoc',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='NifDoc',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='NisDoc',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='RCDoc',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='valide',
            field=models.BooleanField(default=True),
        ),
    ]
