# Generated by Django 4.2.5 on 2024-06-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cordinates'),
        ('tiers', '0011_auto_20240502_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceClient', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('etatProspection', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_prospection', to='tiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutTentative', models.DateTimeField()),
                ('dateFinTentative', models.DateTimeField()),
                ('MoyenContact', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('propspection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_tentative', to='tiers.prospectionclient')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_tentatives', to='users.customuser')),
            ],
        ),
    ]
