# Generated by Django 4.2.5 on 2023-10-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('comptoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcaisse',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='fidelite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
