# Generated by Django 4.2.5 on 2023-10-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientInfo", "0009_store_product_variant"),
        ("produits", "0005_verificationarchive_entrepot"),
        ("comptoire", "0006_comptoircustompermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boncomptoire",
            name="caisse",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientInfo.compteentreprise",
            ),
        ),
        migrations.CreateModel(
            name="ProduitsEnBonComptoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unitprice", models.DecimalField(decimal_places=2, max_digits=15)),
                ("totalprice", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "BonNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_en_bon_comptoir",
                        to="comptoire.boncomptoire",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bons_comptoir",
                        to="produits.product",
                    ),
                ),
            ],
        ),
    ]
