# Generated by Django 4.2.5 on 2023-10-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tiers", "0006_remove_client_actclient"),
        ("users", "0006_alter_customuser_entrepots_responsible"),
        ("comptoire", "0007_boncomptoire_caisse_produitsenboncomptoir"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonRetourComptoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idBon",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="id Bon"
                    ),
                ),
                ("dateBon", models.DateField()),
                (
                    "bon_comptoir_associe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bons_retour_compt",
                        to="comptoire.boncomptoire",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tiers.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_bons_retourcomptoire",
                        to="users.customuser",
                    ),
                ),
            ],
        ),
    ]
