# Generated by Django 4.2.5 on 2023-10-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comptoire", "0009_bonretourcomptoir_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationcaisse",
            name="emplacement",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comptoire.pointvente",
            ),
        ),
    ]
