# Generated by Django 4.2.5 on 2023-10-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_logentry_mylogentry'),
        ('comptoire', '0010_alter_affectationcaisse_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncomptoire',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_comptoire', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='bonretourcomptoir',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retourcomptoire', to='users.customuser'),
        ),
    ]
