# Generated by Django 4.2.5 on 2023-10-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0008_alter_client_user'),
        ('comptoire', '0014_boncomptoire_totalprice_boncomptoire_totalremise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncomptoire',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesbons_comptoir', to='tiers.client'),
        ),
        migrations.AlterField(
            model_name='bonretourcomptoir',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsretour_compt', to='tiers.client'),
        ),
    ]
