# Generated by Django 4.2.5 on 2023-11-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_logentry_mylogentry"),
        ("clientInfo", "0009_store_product_variant"),
        ("comptoire", "0016_alter_cloture_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="verssement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("date", models.DateField()),
                (
                    "bon_comptoir_associe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verssements",
                        to="comptoire.boncomptoire",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientInfo.store",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customuser",
                    ),
                ),
            ],
        ),
    ]
