# Generated by Django 4.2.5 on 2023-11-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('comptoire', '0017_verssement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncomptoire',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_comptoir_store', to='clientInfo.store'),
        ),
    ]
