# Generated by Django 4.2.5 on 2023-12-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptoire', '0018_alter_boncomptoire_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationcaisse',
            name='emplacement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_affectation', to='comptoire.pointvente'),
        ),
    ]
