# Generated by Django 4.2.5 on 2023-10-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_remove_produitsenfacture_pu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
