# Generated by Django 3.2.14 on 2024-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('ventes', '0020_auto_20240213_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='validationBl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_validation', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('codeBl', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('montantBl', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('solde_note', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('client_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_validation', to='users.customuser')),
            ],
        ),
    ]
