# Generated by Django 4.2.5 on 2023-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('num_cheque', models.CharField(blank=True, default='', max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeReglement', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('type_reglement', models.CharField(choices=[('paiement', 'paiement'), ('remboursement', 'remboursement')], max_length=100)),
                ('collected', models.BooleanField(default=False)),
                ('dateReglement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
