# Generated by Django 4.2.5 on 2023-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('reglements', '0001_initial'),
        ('clientInfo', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='BonS',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_reglements', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='CompteEntreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements', to='ventes.facture'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
