# Generated by Django 4.2.5 on 2023-09-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0005_alter_compteentreprise_monnaie'),
        ('reglements', '0003_reglementscustompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancereglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='modereglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
