# Generated by Django 4.2.5 on 2023-10-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_entrepots_responsible'),
        ('tiers', '0005_comptebancaire_compteclient_and_more'),
        ('clientInfo', '0009_store_product_variant'),
        ('achats', '0007_produitsenfactureachat'),
        ('reglements', '0005_reglement_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeReglement', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('type_reglement', models.CharField(choices=[('paiement', 'paiement'), ('remboursement', 'remboursement')], max_length=100)),
                ('collected', models.BooleanField(default=False)),
                ('dateReglement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonA', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonAchats_reglements', to='achats.bonachat')),
                ('CompteEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_reglements', to='clientInfo.compteentreprise')),
                ('facture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factureAchats_reglements', to='achats.factureachat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_reglements', to='tiers.fournisseur')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_typefournisseur', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
