# Generated by Django 4.2.5 on 2023-12-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0007_mouvementcaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pj'),
        ),
    ]
