# Generated by Django 4.2.5 on 2023-12-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('clientInfo', '0009_store_product_variant'),
        ('reglements', '0008_reglement_piece_jointe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salaire', 'Salaire'), ('loyer', 'Loyer'), ('divers', 'Divers')], max_length=20)),
                ('nom_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fonction_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adresse_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tlfn_salarie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('numero_local', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adresse_local', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='clientInfo.compteentreprise')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglement_depense', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('type_depense', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_depenses', to='reglements.typedepense')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
