# Generated by Django 4.2.5 on 2024-01-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('reglements', '0010_mouvementcaisse_compteentreprisedestinataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='montantCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('utilisateur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ClotureReglements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
                ('montant_collected', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('utilisateur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
