# Generated by Django 4.2.5 on 2024-02-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.CharField(default='', max_length=255)),
                ('montanttotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montantperMonth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_months', models.CharField(default='', max_length=255)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_prox_social', to='gestionRH.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.CharField(default='', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_avances_salaire', to='gestionRH.salarie')),
            ],
        ),
    ]
