# Generated by Django 3.2.14 on 2024-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0002_prixsocial_avancesalaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='association',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salarie',
            name='ccp',
            field=models.CharField(default='', max_length=255),
        ),
    ]
