# Generated by Django 4.2.5 on 2024-03-09 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionRH", "0003_auto_20240303_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarie",
            name="datenaiss",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="salarie",
            name="degre",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="echellon",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="fonctionarabe",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="lieu_naissance",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="lieu_naissancearabe",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="nomarabe",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salarie",
            name="num_assurancesocial",
            field=models.CharField(default="", max_length=255),
        ),
    ]
