# Generated by Django 4.2.5 on 2024-03-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0005_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(default='', max_length=255)),
                ('valide', models.BooleanField(default=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_primesmotivation', to='gestionRH.salarie')),
            ],
        ),
    ]
