# Generated by Django 4.2.5 on 2024-03-25 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0010_auto_20240304_1334'),
        ('users', '0010_customuser_adresse_ip'),
        ('gestionRH', '0007_auto_20240318_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequeteSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('objet', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='')),
                ('reponse', models.TextField(default='')),
                ('datereponse', models.DateTimeField(default=datetime.datetime.now)),
                ('destinataire', models.CharField(default='', max_length=255)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
