# Generated by Django 3.2.14 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0010_auto_20240401_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='minusSource',
            field=models.CharField(default='', max_length=255),
        ),
    ]
