# Generated by Django 4.2.5 on 2024-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0011_absence_minussource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event.', max_length=100)),
                ('description', models.TextField(default='', help_text='The name of the event.')),
                ('event_date', models.DateField(help_text='The date of the event.')),
                ('remember_months', models.IntegerField(default=0, help_text='Number of months in advance to remember the event.')),
                ('remind_days_before', models.IntegerField(default=0, help_text='Number of days before the event to send a reminder.')),
            ],
        ),
    ]
