# Generated by Django 4.2.5 on 2024-05-23 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='dateDebut',
            field=models.DateField(default=datetime.datetime.now, help_text='The date of start.'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime.now, help_text='The date of start.'),
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(default=datetime.datetime.now)),
                ('dateFin', models.DateTimeField(default=datetime.datetime.now)),
                ('nbrJourPris', models.IntegerField(default='0')),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_conge', to='gestionRH.salarie')),
            ],
        ),
    ]
