# Generated by Django 4.2.5 on 2024-06-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0013_salarie_datedebut_salarie_dateend_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSortie', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(default='')),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_reglementscompte', to='gestionRH.salarie')),
            ],
        ),
    ]
