# Generated by Django 4.2.5 on 2023-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='type_desc',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
    ]
