# Generated by Django 4.2.5 on 2023-09-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_tierscustompermission'),
        ('clientInfo', '0003_clientinfocustompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteentreprise',
            name='agence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_comptes', to='tiers.agence'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='banque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_comptes', to='tiers.banque'),
        ),
    ]
