# Generated by Django 4.2.5 on 2023-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0008_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_variant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
