# Generated by Django 3.2.14 on 2024-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeclient',
            name='montant_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=150),
        ),
        migrations.AddField(
            model_name='typeclient',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
