# Generated by Django 4.2.5 on 2023-12-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0008_alter_client_user'),
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('ventes', '0015_bonsortie_agencelivraison_bonsortie_fraislivraison'),
        ('clientInfo', '0009_store_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('chauffeur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_depart', models.DateTimeField()),
                ('adresse_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('frais_Livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bonlivraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_transports', to='ventes.bonsortie')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_bonstransport', to='tiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('bon_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_bontransport', to='logistique.bontransport')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_moyenstransport', to='clientInfo.store')),
            ],
        ),
        migrations.AddField(
            model_name='bontransport',
            name='moyen_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.moyentransport'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bontransport', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bonstransport', to='users.customuser'),
        ),
    ]
