# Generated by Django 4.2.5 on 2024-01-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_product_prix_livraison'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitsEnBonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('livre', models.BooleanField(default=False)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transport', to='logistique.bontransport')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transport', to='produits.product')),
            ],
        ),
    ]
