# Generated by Django 4.2.5 on 2024-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0002_produitsenbontransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontransport',
            name='etat_livraison',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
