# Generated by Django 3.2.14 on 2024-03-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0021_validationbl'),
        ('tiers', '0009_region'),
        ('logistique', '0003_bontransport_etat_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='requeteClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReq', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_requetes', to='tiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='BlsEnRequete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bonlivraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_requests', to='ventes.bonsortie')),
            ],
        ),
    ]
