# Generated by Django 4.2.5 on 2024-03-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0021_validationbl'),
        ('logistique', '0004_blsenrequete_requeteclientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlsEnRequeteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bonlivraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_requests', to='ventes.bonsortie')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_enreq', to='logistique.requeteclientinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='BlsEnRequete',
        ),
    ]
