# Generated by Django 3.2.14 on 2024-04-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20240417_0924'),
        ('logistique', '0006_fichelivraisonexterne'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datePrep', models.DateTimeField()),
                ('bonEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsE_preparation', to='inventory.bonentry')),
            ],
        ),
    ]
