# Generated by Django 4.2.5 on 2024-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_adresse_ip'),
        ('ventes', '0024_alter_bonsortie_etat_reglement'),
        ('logistique', '0007_preparationstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dateTimeAffectation', models.DateTimeField(blank=True, null=True)),
                ('dateTimeDebut', models.DateTimeField(blank=True, null=True)),
                ('dateTimeFin', models.DateTimeField(blank=True, null=True)),
                ('typeCourse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transporteur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fraisTransport', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('montantrecupere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tempsCourse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bonlivraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonL_course', to='ventes.bonsortie')),
                ('chauffeur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_courses', to='users.customuser')),
                ('moyen_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='logistique.moyentransport')),
            ],
        ),
    ]
