# Generated by Django 4.2.5 on 2023-10-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('produits', '0005_verificationarchive_entrepot'),
        ('inventory', '0014_bontransfert_automatiquement_bontransfert_valide'),
        ('users', '0005_customuser_entrepots_responsible'),
        ('tiers', '0005_comptebancaire_compteclient_and_more'),
        ('reglements', '0005_reglement_user'),
        ('achats', '0004_achatinfocustompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('destinataire', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('TVA', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.taxes')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_echeance', to='reglements.echeancereglement')),
                ('fournisseur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_commandeachat', to='tiers.fournisseur')),
                ('livraison', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_type', to='reglements.modereglement')),
                ('monnaie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.valeurdevise')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_commandesachat', to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachats', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonCommandesAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_commandeachat', to='achats.boncommandeachat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachat', to='produits.product')),
            ],
        ),
    ]
