# Generated by Django 4.2.5 on 2023-10-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('inventory', '0014_bontransfert_automatiquement_bontransfert_valide'),
        ('reglements', '0005_reglement_user'),
        ('tiers', '0005_comptebancaire_compteclient_and_more'),
        ('produits', '0005_verificationarchive_entrepot'),
        ('users', '0005_customuser_entrepots_responsible'),
        ('achats', '0005_boncommandeachat_produitsenboncommandesachat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('BonAchat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_bonreception', to='achats.bonachat')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_receptions', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixUnitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=0)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reception', to='achats.bonreception')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFacture', models.CharField(max_length=200, unique=True)),
                ('date_facture', models.DateField()),
                ('Remise', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat_reglement', models.CharField(max_length=250)),
                ('shippingCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('BonAchat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_facture', to='achats.bonachat')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_echeance', to='reglements.echeancereglement')),
                ('fournisseur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_facture_achat', to='tiers.fournisseur')),
                ('livraison', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_type', to='reglements.modereglement')),
                ('monnaie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.valeurdevise')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_factureachat', to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_facture_achat', to='users.customuser')),
            ],
        ),
    ]
