# Generated by Django 4.2.5 on 2023-10-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientInfo", "0009_store_product_variant"),
        ("achats", "0008_avoirachat"),
    ]

    operations = [
        migrations.AddField(
            model_name="avoirachat",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientInfo.store",
            ),
        ),
    ]
