# Generated by Django 4.2.5 on 2023-10-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tiers", "0007_client_nif_client_nis_client_num_article_and_more"),
        ("inventory", "0015_bonreforme_bonretour_and_more"),
        ("clientInfo", "0009_store_product_variant"),
        ("users", "0007_logentry"),
        ("achats", "0010_remove_avoirachat_client_avoirachat_fournisseur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonreception",
            name="chauffeur",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bonreception",
            name="entrepot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrepot_bonreception",
                to="inventory.entrepot",
            ),
        ),
        migrations.AddField(
            model_name="bonreception",
            name="immatriculation",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bonreception",
            name="unite_monitaire",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unitemonitaire_bonreception",
                to="clientInfo.valeurdevise",
            ),
        ),
        migrations.AlterField(
            model_name="bonreception",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mes_bons_reception",
                to="users.customuser",
            ),
        ),
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Port_debarquement",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "port_embarquement",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("nombre_colis", models.IntegerField(default=0)),
                (
                    "etat",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("date_depart", models.DateField()),
                ("date_arrive", models.DateField()),
                ("date_remise_transitaire", models.DateField()),
                ("date_domiciliation", models.DateField()),
                ("date_conaissement", models.DateField()),
                ("nbr_jours_port", models.IntegerField(default=0)),
                (
                    "banque_domiciliation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedition_banque",
                        to="tiers.banque",
                    ),
                ),
                (
                    "bon_commande",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedition_commandes",
                        to="achats.boncommandeachat",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientInfo.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_expedition",
                        to="users.customuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bonreception",
            name="expedition",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedition_bonreception",
                to="achats.expedition",
            ),
        ),
    ]
