# Generated by Django 4.2.5 on 2023-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0011_bonreception_chauffeur_bonreception_entrepot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='code_bon',
            field=models.CharField(default='', max_length=200, verbose_name='id Bon'),
        ),
    ]
