# Generated by Django 4.2.5 on 2023-10-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_logentry_mylogentry'),
        ('achats', '0012_expedition_code_bon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_achat', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='boncommandeachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachats', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='bonreception',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='factureachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_facture_achat', to='users.customuser'),
        ),
    ]
