# Generated by Django 3.2.14 on 2024-04-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0010_client_sourceclient'),
        ('users', '0010_customuser_adresse_ip'),
        ('clientInfo', '0010_auto_20240304_1334'),
        ('achats', '0014_bonachat_echeance_reglement_bonachat_entrepot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDossier', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateDossier', models.DateField()),
                ('facture', models.FileField(upload_to='media/document')),
                ('monnaie', models.CharField(default='', max_length=255)),
                ('MontantEtrange', models.DecimalField(decimal_places=2, default=0, max_digits=35)),
                ('TypePaiement', models.CharField(default='', max_length=255)),
                ('AvisDebit', models.FileField(upload_to='media/document')),
                ('datePaiement', models.DateField()),
                ('MontantDZD', models.DecimalField(decimal_places=2, default=0, max_digits=35)),
                ('DateValeur', models.FileField(upload_to='media/document')),
                ('DateMontant', models.FileField(upload_to='media/document')),
                ('TauxChange', models.CharField(default='', max_length=255)),
                ('BonCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_achat_commande', to='achats.boncommandeachat')),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_dossierachat', to='tiers.banque')),
                ('fournisseur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_dossier_achat', to='tiers.fournisseur')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_dossier_achat', to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_dossier_achat', to='users.customuser')),
            ],
        ),
    ]
