# Generated by Django 3.2.14 on 2024-04-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0015_dossierachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierachat',
            name='DateValeurdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dossierachat',
            name='DateMontant',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
