# Generated by Django 4.2.5 on 2024-08-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0016_auto_20240417_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommandeachat',
            name='TVA',
        ),
        migrations.RemoveField(
            model_name='produitsenboncommandesachat',
            name='prixUnitaire',
        ),
        migrations.RemoveField(
            model_name='produitsenboncommandesachat',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='DDtax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='tauxChange',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='ttctax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='DroitRealisation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='Totalcharges',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='anda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='chargesApproximatively',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='chargesPercent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='prixUnitairUSD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='prixUnitaireDZ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='taxesTotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='taxesUnitaire',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='totalPriceDZ',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='totalPriceUSD',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='transportPercent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='transportPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='Tva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
