# Generated by Django 4.2.5 on 2024-08-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0010_auto_20240304_1334'),
        ('users', '0011_cordinates'),
        ('produits', '0020_historiqueachatproduit'),
        ('achats', '0017_remove_boncommandeachat_tva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmission', models.DateField()),
                ('motifCredit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('totalUsd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalDZ', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tauxChange', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonAchat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.bonachat')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProjet', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Marque', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dateProjet', models.DateField()),
                ('designation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cnn', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('FichierProjet', models.FileField(upload_to='media/document')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_projets', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puUsdAchat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('puDaAchat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantityAchete', models.IntegerField(default=0)),
                ('Credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_creditNote', to='achats.creditnote')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_creditNote', to='produits.product')),
            ],
        ),
        migrations.AddField(
            model_name='creditnote',
            name='Projet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.projetcredit'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_creditd', to='users.customuser'),
        ),
    ]
