# Generated by Django 4.2.5 on 2023-10-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0005_verificationarchive_entrepot"),
        ("comptoire", "0008_bonretourcomptoir"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonretourcomptoir",
            name="decision",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.CreateModel(
            name="ProduitsEnBonRetourComptoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalprice", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unitprice", models.DecimalField(decimal_places=2, max_digits=15)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "BonNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_en_bon_retourcomptoir",
                        to="comptoire.bonretourcomptoir",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_bons_retourcomptoir",
                        to="produits.product",
                    ),
                ),
            ],
        ),
    ]
