# Generated by Django 4.2.5 on 2023-10-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_bonentry_user_alter_bonreforme_user_and_more'),
        ('comptoire', '0011_alter_boncomptoire_user_alter_bonretourcomptoir_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretourcomptoir',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_boncomp', to='inventory.entrepot'),
        ),
    ]
