# Generated by Django 4.2.5 on 2023-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptoire', '0013_remove_produitsenbonretourcomptoir_entrepot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncomptoire',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='totalremise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
