# Generated by Django 4.2.5 on 2023-09-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0001_initial'),
        ('tiers', '0002_initial'),
        ('ventes', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretour',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonRetours', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_retour', to='tiers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
