# Generated by Django 4.2.5 on 2023-09-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
        ('inventory', '0004_bonsortiestock_produitsenbonsortiestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortiestock',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsBl_sortiesstock', to='ventes.bonsortie'),
        ),
    ]
