# Generated by Django 4.2.5 on 2023-09-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tiers", "0002_initial"),
        ("produits", "0003_product_reforme"),
        ("clientInfo", "0002_alter_typeclient_type_desc"),
        ("users", "0001_initial"),
        ("inventory", "0005_bonsortiestock_bonl"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonReforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idBon",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="id Bon"
                    ),
                ),
                ("dateBon", models.DateField()),
                ("totalPrice", models.IntegerField(default=0)),
                (
                    "bonR",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="MesbonReforme",
                        to="inventory.bonretour",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_bons_reforme",
                        to="tiers.client",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_bons_reforme",
                        to="clientInfo.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_bons_reforme",
                        to="users.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduitsEnBonReforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NumeroSeries", models.TextField(default="")),
                (
                    "BonNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_en_bon_reforme",
                        to="inventory.bonreforme",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_bons_reforme",
                        to="produits.product",
                    ),
                ),
            ],
        ),
    ]
