# Generated by Django 4.2.5 on 2023-09-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bonreforme_produitsenbonreforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonreforme',
            name='bonR',
        ),
        migrations.RemoveField(
            model_name='bonreforme',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bonreforme',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='produitsenbonreforme',
            name='NumeroSeries',
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bons_reforme', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='produitsenbonreforme',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
