# Generated by Django 4.2.5 on 2023-09-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_bongarantie_bonlivraisonassocie'),
        ('tiers', '0003_tierscustompermission'),
        ('users', '0002_userscustompermission'),
        ('clientInfo', '0003_clientinfocustompermission'),
        ('inventory', '0009_alter_bonsortiestock_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BonSortieStock',
            new_name='Bonsortiedestock',
        ),
    ]
