# Generated by Django 4.2.5 on 2023-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_bonsortiedestock_date_constat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonsortiedestock',
            name='Date_constat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
