# Generated by Django 3.2.14 on 2024-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20240417_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonmaintenance',
            name='decision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_kit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_pc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
