# Generated by Django 4.2.5 on 2023-09-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_rename_bonsortiestock_bonsortiedestock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonsortiedestock",
            name="Date_constat",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="bonsortiedestock",
            name="Date_doc_Sortie",
            field=models.DateField(blank=True, null=True),
        ),
    ]
