# Generated by Django 4.2.5 on 2023-09-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0005_alter_compteentreprise_monnaie'),
        ('produits', '0005_verificationarchive_entrepot'),
        ('users', '0002_userscustompermission'),
        ('inventory', '0012_alter_bonsortiedestock_date_constat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonReintegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('bonRetour', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonretour_bons_reintegration', to='inventory.bonretour')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_reintegration', to='inventory.entrepot')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reintegration', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonReintegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reintegration', to='inventory.bonreintegration')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_reintegration', to='produits.product')),
            ],
        ),
    ]
