# Generated by Django 4.2.5 on 2023-10-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_bontransfert_automatiquement_bontransfert_valide"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonreforme",
            name="bonretour",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bonretour_bon_reforme",
                to="inventory.bonretour",
            ),
        ),
        migrations.AddField(
            model_name="produitsenbonreforme",
            name="observation",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="produitsenbonretour",
            name="reintegrated",
            field=models.BooleanField(default=False),
        ),
    ]
