# Generated by Django 4.2.5 on 2024-01-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0010_product_prix_livraison"),
        ("clientInfo", "0009_store_product_variant"),
        ("inventory", "0016_alter_bonentry_user_alter_bonreforme_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="equipeInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_equipe", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="produitEnInventaireAnnuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "Equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liste_produits",
                        to="inventory.equipeinventaire",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mon_inventaire",
                        to="produits.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventaireAnnuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeInv", models.CharField(max_length=100)),
                ("dateInv", models.DateField()),
                ("datecloture", models.DateField()),
                ("note", models.TextField()),
                (
                    "entrepot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrepot_inventaire",
                        to="inventory.entrepot",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_inventaires",
                        to="clientInfo.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipeinventaire",
            name="inv_annuel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventaire_assosiated",
                to="inventory.inventaireannuel",
            ),
        ),
    ]
