# Generated by Django 4.2.5 on 2024-01-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_equipeinventaire_produiteninventaireannuel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity_initial",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
