# Generated by Django 4.2.5 on 2024-01-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_region'),
        ('produits', '0010_product_prix_livraison'),
        ('clientInfo', '0009_store_product_variant'),
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('inventory', '0018_stock_quantity_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('observation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bonretour',
            name='valide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='ProduitsEnBonMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, default='', null=True)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_maintenance', to='inventory.bonmaintenance')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_echange', to='inventory.bonechange')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_echange', to='produits.product')),
            ],
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsmaintenance', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_maintenance', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonechange', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_echange', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsechange', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_echange', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_echange', to='users.customuser'),
        ),
    ]
