# Generated by Django 4.2.5 on 2024-02-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
        ('clientInfo', '0009_store_product_variant'),
        ('inventory', '0019_bonechange_bonmaintenance_bonretour_valide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonTransfertMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('automatiquement', models.BooleanField(blank=True, default=False, null=True)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('entrepot_arrive', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entarr_transfertmag', to='inventory.entrepot')),
                ('entrepot_depart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entdep_transfertmag', to='inventory.entrepot')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('store_arrive', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_arr', to='clientInfo.store')),
                ('store_depart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_dep', to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transfert_mag', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonTransfertMag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transfertMag', to='inventory.bontransfertmagasin')),
                ('stock_arr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_recu', to='inventory.stock')),
                ('stock_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_arrive', to='inventory.stock')),
            ],
        ),
    ]
