# Generated by Django 4.2.5 on 2024-02-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptoire', '0019_alter_affectationcaisse_emplacement'),
        ('inventory', '0020_bontransfertmagasin_produitsenbontransfertmag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonLComptoir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonmaintenanceComptoir', to='comptoire.bonretourcomptoir'),
        ),
    ]
