# Generated by Django 3.2.14 on 2024-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_bonmaintenance_bonlcomptoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_blocked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
