# Generated by Django 4.2.5 on 2024-03-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_stock_quantity_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="bontransfert",
            name="received",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="produitsenbonretour",
            name="numseries",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="produitsenbonretour",
            name="warranty",
            field=models.BooleanField(default=False),
        ),
    ]
