# Generated by Django 3.2.14 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_bonretourancien_produitsenbonretourancien'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='image1',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='image2',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='image3',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='image4',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='image',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsenbonretourancien',
            name='image',
            field=models.FileField(default=1, upload_to='media/document'),
            preserve_default=False,
        ),
    ]
