# Generated by Django 3.2.14 on 2024-05-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20240423_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretourancien'),
        ),
    ]
