# Generated by Django 4.2.5 on 2024-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_bonmaintenance_bonr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretour',
            name='reception_valide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
