# Generated by Django 4.2.5 on 2024-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_bonretour_reception_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bontransfert',
            name='received',
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='annule',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='validation_recu',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
