# Generated by Django 4.2.5 on 2024-02-22 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0009_store_product_variant'),
        ('users', '0009_alter_customuser_entrepots_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('fonction', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('cout_heure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_espece', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Renumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrive', models.DateTimeField()),
                ('salaire_declare', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('salaire_espece', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionRH.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('temps_arrive', models.TimeField(default='09:00:00')),
                ('temps_depart', models.TimeField(default='17:00:00')),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_pointage', to='gestionRH.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='HeureSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heure', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('datetimedeb', models.DateTimeField(default=datetime.datetime.now)),
                ('datetimeend', models.DateTimeField(default=datetime.datetime.now)),
                ('motif', models.CharField(default='', max_length=255)),
                ('valide', models.BooleanField(default=True)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_heure_sup', to='gestionRH.salarie')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nombre_heure', models.CharField(default='', max_length=255)),
                ('motif', models.CharField(default='', max_length=255)),
                ('justifie', models.BooleanField(default=False)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_absences', to='gestionRH.salarie')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
