# Generated by Django 4.2.5 on 2024-03-12 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0004_salarie_datenaiss_salarie_degre_salarie_echellon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(default='', max_length=255)),
                ('numero_decision_recrutement', models.CharField(default='', max_length=255)),
                ('numero_pv_installation', models.CharField(default='', max_length=255)),
                ('datedeb', models.DateTimeField(default=datetime.datetime.now)),
                ('datesignature', models.DateTimeField(default=datetime.datetime.now)),
                ('datefin', models.DateTimeField(default=datetime.datetime.now)),
                ('type_contrat', models.CharField(default='', max_length=255)),
                ('salarie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_contrat', to='gestionRH.salarie')),
            ],
        ),
    ]
