# Generated by Django 3.2.14 on 2024-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0009_boitearchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitearchive',
            name='date_facturation_fournisseur',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boitearchive',
            name='date_facturation_transitaire',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boitearchive',
            name='document',
            field=models.FileField(upload_to='media/document'),
        ),
    ]
