# Generated by Django 4.2.5 on 2023-09-24 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('clientInfo', '0001_initial'),
        ('produits', '0001_initial'),
        ('users', '0001_initial'),
        ('reglements', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField(default=datetime.datetime.now)),
                ('date_reglement', models.DateField(default=datetime.datetime.now)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS_commande', to='tiers.client')),
                ('echeance_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglements.echeancereglement')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_reglements_type', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commande', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS_devis', to='tiers.client')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_devis', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('etat_reglement', models.CharField(choices=[('non-regle', 'non-regle'), ('regle', 'regle')], default='non-regle', max_length=30)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_reglements_bonL', to='tiers.banque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bonS', to='tiers.client')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bons', to='inventory.entrepot')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_store', to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFacture', models.CharField(max_length=200, unique=True)),
                ('date_facture', models.DateField()),
                ('date_reglement', models.DateField(default=datetime.datetime.now)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat_reglement', models.CharField(choices=[('en Attente', 'en Attente'), ('Règlement Reçu', 'Règlement Reçu'), ('Expédié', 'Expédié'), ('Facture', 'Facture'), ('Facture Comptabilisé', 'Facture Comptabilisé')], max_length=30)),
                ('shippingCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('BonS', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_facture', to='ventes.boncommande')),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_reglements', to='tiers.banque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_facture', to='tiers.client')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements_echeance', to='reglements.echeancereglement')),
                ('mode_reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements_type', to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('FactureNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_facture', to='ventes.facture')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_sorties', to='ventes.bonsortie')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesproduit_bons_sortie', to='inventory.entrepot')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_sortie', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroSeries', models.TextField(default='')),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_garantie', to='ventes.bongarantie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_garantie', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_devis', to='ventes.bondevis')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_devis', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_commande', to='ventes.boncommande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commande', to='produits.product')),
            ],
        ),
        migrations.AddField(
            model_name='bongarantie',
            name='bonLivraisonAssocie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_garantie', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bongarantie',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bongarantie',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bongarantie',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_garantie', to='users.customuser'),
        ),
    ]
