# Generated by Django 4.2.5 on 2023-09-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes", "0003_alter_bongarantie_bonlivraisonassocie"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitsenbongarantie",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
