# Generated by Django 4.2.5 on 2023-09-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0004_echeancereglement_store_modereglement_store'),
        ('ventes', '0004_produitsenbongarantie_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_reglements_type', to='reglements.modereglement'),
        ),
    ]
