# Generated by Django 4.2.5 on 2023-10-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_bonsortie_echeance_reglement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='BonS',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_facture', to='ventes.bonsortie'),
        ),
    ]
