# Generated by Django 4.2.5 on 2023-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_alter_facture_bons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenfacture',
            name='pu',
        ),
        migrations.AddField(
            model_name='produitsenfacture',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='produitsenfacture',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='produitsenfacture',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
