# Generated by Django 4.2.5 on 2023-10-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes", "0008_facture_totalprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="Remise",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
