# Generated by Django 4.2.5 on 2023-10-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reglements", "0006_reglementfournisseur"),
        ("ventes", "0009_alter_facture_remise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="mode_reglement",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facture_reglements_type",
                to="reglements.modereglement",
            ),
        ),
    ]
