# Generated by Django 4.2.5 on 2023-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes", "0012_avoirvente_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="avoirvente",
            name="montant",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="avoirvente",
            name="motif",
            field=models.CharField(default="", max_length=200),
        ),
    ]
