# Generated by Django 4.2.5 on 2023-10-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_logentry_mylogentry'),
        ('ventes', '0013_avoirvente_montant_alter_avoirvente_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commande', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='bondevis',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_devis', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='bongarantie',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_garantie', to='users.customuser'),
        ),
    ]
