# Generated by Django 4.2.5 on 2023-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes", "0014_alter_boncommande_user_alter_bondevis_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonsortie",
            name="agenceLivraison",
            field=models.CharField(blank=True, default="", max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="bonsortie",
            name="fraisLivraison",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
