# Generated by Django 4.2.5 on 2024-01-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0017_bonsortie_fraislivraisonexterne'),
    ]

    operations = [
        migrations.AddField(
            model_name='bongarantie',
            name='tps_ecoule',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
