# Generated by Django 3.2.14 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0021_validationbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbongarantie',
            name='livre',
            field=models.BooleanField(default=False),
        ),
    ]
