# Generated by Django 3.2.14 on 2024-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0022_produitsenbongarantie_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='typebl',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
