# Generated by Django 4.2.5 on 2024-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0023_auto_20240418_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonsortie',
            name='etat_reglement',
            field=models.CharField(default='', max_length=30),
        ),
    ]
