# Generated by Django 4.2.5 on 2024-07-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0025_produitsenbonsortie_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonsortie',
            name='etat_reglement',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
