# Generated by Django 4.2.5 on 2023-09-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0005_alter_compteentreprise_monnaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurDevise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('date', models.DateField(blank=True, default='2023-08-22', null=True)),
                ('Devise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.devise')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_devises_valeur', to='clientInfo.store')),
            ],
        ),
    ]
