# Generated by Django 4.2.5 on 2024-10-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitProductionBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ProdPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bl', to='production.produitsenordrefabrication')),
            ],
        ),
    ]
