# Generated by Django 4.2.5 on 2024-10-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0028_bonsortie_confirmed_confirmationbl'),
        ('production', '0002_produitproductionbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitproductionbl',
            name='ProdenBL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_PEnOrdre', to='ventes.produitsenbonsortie'),
        ),
    ]
