# Generated by Django 4.2.5 on 2023-10-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userscustompermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
