# Generated by Django 4.2.5 on 2023-10-17 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientInfo", "0009_store_product_variant"),
        ("users", "0007_logentry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LogEntry",
            new_name="MyLogEntry",
        ),
    ]
