# Generated by Django 4.2.5 on 2024-05-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_adresse_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='cordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycoordinates', to='users.customuser')),
            ],
        ),
    ]
